name: Adam Londero, SFW Ltd.
markdown: kramdown
baseurl: /techradar

collections:
  languagesandframeworks:
    output: true
  techniques:
    output: true
  tools:
    output: true
  platforms:
    output: true